### PR TITLE
Adding new home page design

### PR DESCRIPTION
**Pull request by DreamsOfImran**
* Added new home page design #6 
* Fixed ESlint errors and warnings.

### CODE REVIEW

**Comment by sushrut111** [comment]
I did not check where exactly, but there is some issue.
When I put a name in the greet yourself box, it momentarily updates the greeting to say "Hello ${my-name}" and then resets itself to "Hello World!". Can you please fix that?

**Review by sushrut111 — CHANGES_REQUESTED** [review]
Please check my comment on the pull request and fix the issues which are currently hindering the functionality!

**Comment by DreamsOfImran** [comment]
> Please check my comment on the pull request and fix the issues which are currently hindering the functionality!

Thank you for your comment. Fixed that issue. Can you please check again?

**Review by sushrut111 — APPROVED** [review]
The changes look good, thank you!

**Comment by DreamsOfImran** [comment]
You're welcome. Please add **hacktoberfest-accepted** label on this PR.

**Comment by sushrut111** [comment]
I have added proper labels, please verify! @DreamsOfImran

**Comment by DreamsOfImran** [comment]
@sushrut111 It works now!
Thank you 👍 😃

**Pull request merged**
